version: "3.4"

services:


  backend:
    image: "restaurantreviews-backend"
    
    
    
    build:
      
      context: ./
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
    - ./appsettings.json:/app/appsettings.json
    container_name: backend
 
      
     

    depends_on:
      - db
    
  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-db
    networks:
      - backend-network
   

networks:
  backend-network:
    driver: bridge
   
  
volumes:
    mongo-data:
      driver: local
  